# Generated by Django 3.2.4 on 2023-01-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('code', models.TextField(blank=True, default=None, null=True)),
                ('solution', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
